# ['fbresnet152', 'bninception', 'resnext101_32x4d', 'resnext101_64x4d', 'inceptionv4', 'inceptionresnetv2',
# 'alexnet', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'resnet18', 'resnet34', 'resnet50',
# 'resnet101', 'resnet152', 'inceptionv3', 'squeezenet1_0', 'squeezenet1_1', 'vgg11', 'vgg11_bn', 'vgg13',
# 'vgg13_bn', 'vgg16', 'vgg16_bn', 'vgg19_bn', 'vgg19', 'nasnetamobile', 'nasnetalarge', 'dpn68', 'dpn68b', 'dpn92',
# 'dpn98', 'dpn131', 'dpn107', 'xception', 'senet154', 'se_resnet50', 'se_resnet101', 'se_resnet152',
# 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'cafferesnet101', 'pnasnet5large', 'polynet']

DATA_DIR: 'data/train_images_ben_sigma30_512'
CSV: 'data/folds/train+2015_6fold_1.csv'

TRAIN_DIR: '_results/effb3_300_rotate_zoom_addfc_6fold_1_bigger_batch'

PARALLEL: False
DEBUG: False
DEBUG_IMAGE: False
PRINT_EVERY: 10

NUM_WORKERS: 4

TRAIN:
  BATCH_SIZE: 64
  NUM_EPOCHS: 30

EVAL:
  BATCH_SIZE: 64

DATA:
  IMG_H: 300
  IMG_W: 300

MODEL:
  NAME: 'efficientnet-b3'
  FC_TYPE: 1

LOSS:
  NAME: 'mse'

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001
  PARAMS:

SCHEDULER:
  NAME: 'multi_step'
  PARAMS:
    milestones: [3,6,9,15]
    gamma: 0.5
